apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
  namespace: backend-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bandersaeed94/la79y:backend-v11
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: '8080'
        - name: JWT_SECRET
          value: "4b8e5678fa4c46d5b5f6a2295d50b224"
        - name: DB_NAME
          value: "la79y"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_HOST
          value: "postgres.backend-namespace"
        - name: GCP_CLIENT_ID
          value: "<GCP_CLIENT_ID>"
        - name: GCP_CLIENT_SECRET
          value: "<GCP_CLIENT_SECRET>"
        - name: GCP_REFRESH_TOKEN
          value: "<GCP_REFRESH_TOKEN>"
        - name: WEB_PROTO
          value: "http"
        - name: WEB_HOST
          value: "localhost"
        - name: WEB_PORT
          value: "3000"
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "600Mi"
            cpu: "500m"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-namespace
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: http-443
    port: 443
    targetPort: 8080
    protocol: TCP
  - name: http-80
    port: 80
    targetPort: 8080
    protocol: TCP

